---
version: "2.1"
services:
  webtop:
    build: .
    container_name: webtop-vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - TITLE=job
#     volumes:
#       - ./data:/config
#       - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    restart: always
